# fly.toml app configuration file generated for messenger-95 on 2023-08-30T14:41:51-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "messenger-95"
primary_region = "lax"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
